spring:
  profiles:
    active: dev
  application:
    name: skylebank-backend
  jackson:
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
