CREATE TABLE wallets (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    wallet_number VARCHAR(10) UNIQUE NOT NULL,
    balance NUMERIC(15,2) NOT NULL DEFAULT 1000000.00,
    currency VARCHAR(3) NOT NULL DEFAULT 'NGN',
    wallet_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
